// Code generated by "esc -o data.go -pkg=fixtures topo-sort"; DO NOT EDIT.

package tests

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return fis[0:limit], nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// FS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func FS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// Dir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func Dir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// FSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func FSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// FSMustByte is the same as FSByte, but panics if name is not present.
func FSMustByte(useLocal bool, name string) []byte {
	b, err := FSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// FSString is the string version of FSByte.
func FSString(useLocal bool, name string) (string, error) {
	b, err := FSByte(useLocal, name)
	return string(b), err
}

// FSMustString is the string version of FSMustByte.
func FSMustString(useLocal bool, name string) string {
	return string(FSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/topo-sort/.git/COMMIT_EDITMSG": {
		name:    "COMMIT_EDITMSG",
		local:   "topo-sort/.git/COMMIT_EDITMSG",
		size:    229,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/0yPwUrEQBBEz85XFPRhL5IP2Jt4FfQXOunaZCDTIz2tcf9e1hXxWFC8V/VkRkOoW2+4
1J1F8LZTB0FPBnIjlt5aTTSOoStx6YFr/wgsm/rKMeGlOgdGamT1tQiOmhtOcsJR9x0zUVfvQXuEukEd
bO95/SPq3CPHP9dUpAheHXOoLxuMn0XwfPch+w15bybtXOTBefzMPwO/b25pyq8sUr4DAAD//wnszPvl
AAAA
`,
	},

	"/topo-sort/.git/FETCH_HEAD": {
		name:    "FETCH_HEAD",
		local:   "topo-sort/.git/FETCH_HEAD",
		size:    182,
		modtime: 1635261563,
		compressed: `
H4sIAAAAAAAC/3zNQRKCMAwAwDO+ghsnNDShpf4mDSkwI8Qp1Rl/782jH9jNDgZQjeSYQlIB4aBTBnIE
0U/KowMIODZNKnzI2nazvrvWcrtsdX2lq9h+f2yfW7Wn9aeVepE4hIAiODOKE5Q4kneeIXkmEmSJihpd
c1jts5V+17Loz9/5rFr+F98AAAD//9mh0Um2AAAA
`,
	},

	"/topo-sort/.git/HEAD": {
		name:    "HEAD",
		local:   "topo-sort/.git/HEAD",
		size:    20,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/ypKTbNSKEpNK9bPSE1MKdZPSS3jAgQAAP//0aw4/hQAAAA=
`,
	},

	"/topo-sort/.git/config": {
		name:    "config",
		local:   "topo-sort/.git/config",
		size:    351,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/4yPQWr0MAxG1/YpRJbz80+6HjD0HmEWTiI7orYVJCWQ25cmlJlllw/e94SGiQWf3gmu
rGQsR2Kp0XYUJW4Q4MO7RAUrzwgBUiyK3o1R3qhwjqUIpm2do6FCAJMNvdOjFmpf+lIpNxacouKvNAhW
NoSOhTK17undJgUCZLLPTLZs433i+ih09MYr/1cWu2cy7xLatECAf4JJ+wXjrP3tccIV1f6K9jc/jBLb
tEBXoxpKd/58Hg5wSd5VlPzDb7nLfq1n3P86nXH33wEAAP//iH3lo18BAAA=
`,
	},

	"/topo-sort/.git/description": {
		name:    "description",
		local:   "topo-sort/.git/description",
		size:    73,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/wrNy0vMTU1RKEotyC/OLMkvqrRWSE3JLFEoycgsVkjLzElVUE9JLU4uyiwoyczPU1co
yVcA6VAoyUhF0qTHBQgAAP//N4sHH0kAAAA=
`,
	},

	"/topo-sort/.git/hooks/applypatch-msg.sample": {
		name:    "applypatch-msg.sample",
		local:   "topo-sort/.git/hooks/applypatch-msg.sample",
		size:    478,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/1SP3YoTQRBG7/spPjthUbQTvBUEfQdfoDKpTBfpP7pq3FnFd5dOnN14WxzO+Wr37niS
ctTodm6H7wW8Um6JEWu9QqcuzWAVU+TpCouMqeYshlRnZFalmWF05YLTi9uBWksvjWyKuPSaQQUcMkna
4MMt9CNuhViXdAavYngWiyi1hF/cK9TIFgVdjDtEdZEyg8q90WvrQsavE+SCYaBiOuaq1faw9oC3ouhQ
pFSf+TxQPos9PrYZL5K2sRVc6JQYFkVvlk/oXCj/uwx0qPzb9yHr7A/OHTCLBY1B2Zbm7o2s81e/fz+L
ofPP0KgrI4RBNrJ4K+jxzg7RB++M1RBW+P2rwuPpCbzy9P9x//vzR7//5v+4L+5vAAAA//+FT/gJ3gEA
AA==
`,
	},

	"/topo-sort/.git/hooks/commit-msg.sample": {
		name:    "commit-msg.sample",
		local:   "topo-sort/.git/hooks/commit-msg.sample",
		size:    896,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/3xSX0/bPhR9rj/F+SXVr4BIo+5xEpVgTBsvQxrlaazISW5jC8cO9s2Arfvukx06uj/a
SxQdHZ8/9978v7LStgxK5CLHqQU9yq43BOXcHULtdc9gh1pRfQdWhNp1nWYY16KjEGRLc5HjjTSGGlRP
yFrNz6QMD5oVnCVI3w4dWT5OGlZ2BLdJ/xttSORgJRlKhn2PnT6wUrtEyg2mAT1qHsWts8VX8k7kCCx5
CJAbJg8dwqBtC2kh+9673mvJtJOE3iAqSMsh1gvs+ugs8mfvfU8dII1xD9REKjWa/xIy9ZinKa4cyMrK
EFjpkDSO4SmVTkikRqlslCi60GZzIXJc24iQHQ0qMu4h8mTTQOJKt5aawm02RfUEo23SiMS9PZy7WDq5
aAv5UgCVbKAbkhFvyZKX5hjVMFr1nnrpqXgJJPKfbzvnCWHQPA5A81jz6vLsZHoQt/1Fery7WN2eXq/e
X368vTh/+2GFLQI1KCxmoVzfHMyPljeH86Np+UuN17hZlP3sUORoPfUo7gOy9fTq8ixDNl1k2G5BtXLI
Rmy5THCc1Sp23F1rLblWFNAMvdF1XPSf0wpzIZgCI8twgmx6kBxn698CzZ6NxQTBecYWg9X3KOpdI8Ks
XH/C5PPRIn7LZnaYcn4TkxR1+f8rnP87xyTd70J8Fz8CAAD//+n4yhCAAwAA
`,
	},

	"/topo-sort/.git/hooks/fsmonitor-watchman.sample": {
		name:    "fsmonitor-watchman.sample",
		local:   "topo-sort/.git/hooks/fsmonitor-watchman.sample",
		size:    4655,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/6xXX2/bOBJ/lj7FlDZgu7CltPdysOtcF+3uXg+LNmjT2wOarkFLI4mNTKokFdfIup/9
MCRlO3Gapnf7ZlMzw9/8+82w9yhtjU6XQqYN6jqOW4NgrBaZnbnfa66lkKXx/16dvZhO3zQon87iuAc/
ScAvfNXUCJVSl2AyLRoLVoGQFkvNLcLv3GbVisu4B8PK2sZM07TgGS6VukxKYat2mQiVroNYOoK1sBWU
wtkxDWIObQM5WsyskGXcA4lr4DKHlcpFITCHQtRokrgX9+C8CliEgYYbgzlwuEJthJIwzFqtUdp6A09H
zkTNjYW2yQmpVZdIMAulV9xa0jTAXTRk6aRVa5vWGgfM5qq1wB2YQwMkGPeA17WHBbbiFip+hbBElHvQ
RsgMwVZ4Qz2BM24rA6vW2LgHSwSNNbfiir47aa2UBVW432ulLwmc1YgOocGGU9hzWG4Iu5BljfD6/W8h
OgpQ8mVN9wrjAjUGjZKvwglBpovY5xb1ZtJlhQXjBGlAqcmULEQJmdKYFGalpLBKA+UzJaMmvak/iHvx
agPDfsjEGPoU+YX3fOE8H8Ecnv/09td/u9J6LzO1WqG0lA7IcdmWpc9+o4W08O785c9v3wLrn0Bn9A6b
F5I5ay8qzC5dxHxtSIuairCrjFgUe3AgkcrjOo5ygcDeS9M2jdIUVO/V3mFnrVMbdAYGyYVkkMQRAAD7
hdc15WjJCYICk3FJLZUkiYO3jSk0/VLYBaVz4XI5hxL9fyHLRS70cDTzchqt3sAcnoT/n4ySi+aynMV4
xWtCrfFzKzTCv969eT2d/ufdLI52UjAH1p2zWRw9mcVboACrY82zs7s1z84I9SyOa97KrFp0SXYQTbuE
W+dkmZAqmEN3tnCRJI2IQi/M3nevh/mwr0YuC5Fvu4VG09Z22FeT0+usVtnldgzPr91f12nbLZnbUkAJ
xQ2tgGHYd4oiH8Nzp+OKbjGL4+ibJbfDHCySqGpQwpCcKqoxsFM2BuaKv5OdeNlEtZYRqh4shVypHIPG
tLXF35n74Ou5X1TAOnQX0qNz9RH1IKuVcZoEtDP07vzlm/fnh7aCpWBkd8AuTuhrrTJeQ39MifQn/rO/
ataFbZchZ6bLnUbTKGmoMD9/2XkJXobdLF6WzkLr/MJFjTkVfYk2CIscXK/cUNl1TPSddgFRQP8f8GgO
JxQLjbbVct8Ek1OJ68kpBWRymmOmchzusI+OfXRV2PnYiBzmLrVPhxePX/zzt5cLF+Dw+9XrMQx2nk8+
wWQi1aTRaO1mMIojqhly2hsYQeGcn0L/UfDtu0xAqX4lHU15YPil0WgcuSyxVmtY40AjcONIn6qUmNvQ
NNjPGlcwFZflbsYc8yIsWwtSWSi0WrkLqXqhUHWOOomjHhk5V8CzTK2aWpjKjYdxANAaN3QqBOZuYFCi
RM2JEq0C2hRshWRDY4Yy24CQOX5xPmONmYWMy1y4qSdVjsaNF1YIrHPDSKwWK1oAvBHfS3TsxlPwWdab
hMa9PAa1jxsDi3oFVpGdotW2Qk3Dy1jNhQ+1JwiTeCYy7dJYPTwO2RhOxvBkBPgZWMY8Md0RWGoudscg
Ysxxkys0n9w5PHvGop9fv6Qv0Qc/cYlIbnXT2F0VhUhP78jm2H0P0ZvCB0YRYh/98UEs3Cdl2Rg+sFxo
JxWIi338GEfR9mNMgO5lQ7d2dF3gMD+MEJ1oQo0aCHHPez4gx0znJULz7aW8TDieHfETjbLAdekMnnV9
fLqdPcwv6Gzt/fqmU53oN/zqPh+75piiW42nQJCoBTyfYQ5ShapPHkYejhd3QaAaZbPv3yLkFa9Ft9dO
9xYeeGkrazTmMPpfIf3j4jr9P7j5rlVgN7090G5ou8yj1krDHMK3yem1O9mGzSLsS6dw4jgmiB/8nH+F
VdqGpVhR8lV9Fbbs5DHkQmNmld7AMHk8olcF0WbAlQYacHdMJtTH9wxLX113Dcvb03LFLw+azOt9c2I+
YMm8MTWjKISKgvbQ5ETRfYG+XWhe9odmutOgsvmRRex/2cRud2LU2z1RYS3qGni95hsTmuTgHaf8uCiE
NjbMZ6OcfhB1X+k9yfAK9cZWhFkYKiG7YVDUvHSrkLCu/nLl59shAG/2U2tstzQJC+oKtX8US7UGo2BN
Dz85sNDwjdOnmzNlLAjZPZxrepm0DSDPKpq+4krkLfe+JKFObyzkbjsbfi/Vf3Gu79nshyxlIw/nril7
IOss+ccPHD1JwNVnyNCJm8Hx/S78kAfB8JMdfd16tnW75cFRR0x/vCHuGazMxgzgzz+hO8g25VrIQaCW
Q1tz+F3Ivz2dTn9F+2Kdh2TdkPgKVqcXF+lFSryyBawNOkPd0+7FOj/WotPpNAsmtwfkfQP3Nv5vAAAA
//9QuZhjLxIAAA==
`,
	},

	"/topo-sort/.git/hooks/post-update.sample": {
		name:    "post-update.sample",
		local:   "topo-sort/.git/hooks/post-update.sample",
		size:    189,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/yzMwW2EQAyF4ftU8bJzDbs1pIc0YOARRruMLdsg0n0Ukuv/S199e4ytP2IttVR8dPCU
zV7EqvpETN4skQpzmjghMJmenOE0jZbq31jUsQehB71UzPs2Il16mHrG/ZI/FewyvohcW1z6O5xdtv+y
tN+nuJlGDrvNkrzdS+HJCV8t8ZeGoB/0ofVFy08AAAD//5oM98C9AAAA
`,
	},

	"/topo-sort/.git/hooks/pre-applypatch.sample": {
		name:    "pre-applypatch.sample",
		local:   "topo-sort/.git/hooks/pre-applypatch.sample",
		size:    424,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/1SPUY7bMAxE/3WKqWwELVol6G+BAu0degHaoS2itiSIdOK02Lsv7CS72N/h4L1h8+nU
STppdI1r8DuBV5rLxIg5/4X2VYrBMi5cZbjhGskgCurysucdo8/zLGZ8dg26G6iU6VbI+oih5hmUwGEm
mTCzKo183FV/4tMR8zKdwasYrmIRKafwj2uGGtmioMG4QlQXSSMouWZz1FyqkPGTChmwESiZbsPUcoHF
57yHNIMTdRPDouju/4bKieZHMsh2y/Clcnj/xB+dO2IUCxqDsi3Flcp38k/ffh7FUPkSClVlhLA1C1nc
DXraYPfyF++M1RBW+PYN4XE4gFfuP4bt/+9fffvLv7gf7jUAAP//z8BMAqgBAAA=
`,
	},

	"/topo-sort/.git/hooks/pre-commit.sample": {
		name:    "pre-commit.sample",
		local:   "topo-sort/.git/hooks/pre-commit.sample",
		size:    1643,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/2xUUW8bNxN8Nn/FRArsGDDPcR7zxQEMfylqIGiBJkAfkqDgHfd0rCjystyTrCDoby+W
Jyk1kDdRu7c7Mzu7y2fXbUjXZTBLs8RdAj26zRgJQ85rlI7DKJCMLXHo99gNThAKXJun+n9L6PJmE0TI
N2aJexcjebR7LFZBDrEFdkEGpAzHq2lDSUoDfByOXYY8RW+WoMcgx9RkvxFnFHEyFbheiBFKmUJawSW4
ceQ8cnBC2FApbkUIvVlCK7gkRcEVySNkOEJsKsePGZRcGwkyhFIRXIEpuc3hnz5oLGMxMtkDgcaY0EMZ
MW3t6LgQrD2I8uu7u//j7bWn7XWaYsSrt+c3RgZK5sytXEhFbjXFUCxkzpZ4SEGCiwdUr+FD3+OQqdxo
M8oewkTI7d/UyY86z18ohsGVwc4hWJkzT+0vTR+MWeKhxz5PVQxl42LMu6rr3Yf7h4fKUjkXFJKZ+NZx
mIXJEJ6oMfWjlJMrXQiH5l1OfVjBWtmPdNvmHKuGpXmSfKkQ/iAfWEHmScbZL0U8MTeGHqnDzdvzV5p3
z7kUjNFJn3mDkbNSKxBKvmLf5uB/hv1/GJm2lMQsdc4b9Jw3aKmaxHuqX6sBmMZcgmTeN/iTQI9jzEFq
qHed/nD1ZZYYOSSpMrBLK1IHshTMcZTRdYRucOw6taRLHpR8mW0rIXpq1CqfsHj+RJAFnt1iobIu8AXn
52qE37LQqTWmQsg9WnbdmrQj5yl5OAgfoISCvMZATFd4EeSiaBHlD6avU2DyV+gzY8wsrg0xqI0yPuTo
OBTcvLwouJ4K15UXvrxCCamrnqzcvk6O6QgA7V6oYHDjSEnL9C5GhFRTPZWwSk7Iz9AacyZUBLNFqqGt
7Vw3kIe1OiubU9zDWo3ZPkQhvr2D/YbnR+d/N2fA+/u/7t6/v71X0tbj4hPsP18+v7zAd+w62O5SZXx5
2K7OCd68+fzu91/MO+bMr3EnottTTeNVu6emgSJpjPmodu9cQudU9ZFzG2lTEJ7uzC7zeh7sSFmPYk7I
MhCfvFq0WL2Cs+aR9ADpgfTbUI7LdLouVFE0xhyWc53ybr6p+lLxfVbv6kvh+WONinegbo2phLR6bQzw
n2X8yQLWDTYqzVk9qzc/zoIyoNptNwSh2dKkApar2f4Vau57Sl7hnKQr1e+9C/Gwwcdp25A8PerMK8jT
7E/Dtdb8GwAA///vszIMawYAAA==
`,
	},

	"/topo-sort/.git/hooks/pre-merge-commit.sample": {
		name:    "pre-merge-commit.sample",
		local:   "topo-sort/.git/hooks/pre-merge-commit.sample",
		size:    416,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/3yPvW7jMBCEez7FnHRwdZL66w4XIHAbuA9W1kpcRPwBdxXLefpAstyG5XC+4cf6V9dL
7NS72tX4F8ErhTwzfEof0GuRbLCETy4y3nHzZBAF9WnZ855xTSGIGQ+tq/Gf5pkH9HdUkxgCl4kr3MQ8
YgKVaQkcTVvg4p+P+LTMg6vBq9izGpsvLglqZIuCRuMCUV0kTqAIyrmkXISMEViVJoYlV0Nt4FIgI7Yt
iqabpVrKMM8Pn8O43b98SeBI/cwwL7ob/UHhSOFIRtnuEqpcuNn55sFXrXMtJrFGfaNsS3bGamhWVL9f
z5f3l/Nbt+1pt6EHhNPJ4Ti88vWnrvvrvgMAAP//RD/zXqABAAA=
`,
	},

	"/topo-sort/.git/hooks/pre-push.sample": {
		name:    "pre-push.sample",
		local:   "topo-sort/.git/hooks/pre-push.sample",
		size:    1374,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/4RUXWvsNhB9tn7Fqb10byDO11svSaBcKF0ol1B6yUNpi2yNV2pkyZXGcVL644skb3ZT
CvfBMJY0Z845M1LzzWVn3GXUQjT43oFe5DhZgvb+CbEPZmKwxzMFM7xi0ZJhImTn57zeEaY5alIXwCdp
LSl0r6j3hkWTd2rIgSnAMLSM6DX1T6TAmhBo9EyILHmO5+hmRkeDDwTpXlkbt88pHZFbwXKZ3QDWJh7I
0YvhiMWwhoTzrv2bgl9B4XzBWYy1J1xFIxr8kkCyTBPRF+4ZJnEbvLV+SamTDHIkphA/5rTNNdoWn+VI
8MOpDvZYtOlLfiqUcDtKGMo7Sqk3KfXLzz99/axoks60U+izTobPMf1JODmSequrfSTIsJ9HctmKopX+
mqUtUndu8GGUbLw7tE4Tej+O2bvMRAZaGRSTEqM4T5M1pCAjrHEUwV40OTmydEoGBeOmmWHcalsYi03A
rfW9tAg03B9ib9Q9blfeZWP9STvHrsQyg1H7JbVoSX5NgZ7JcXHLDyfsKVAubv0eI8Uo95le4Cia0tH6
cfdQ48Piw1NiOgW/DxTj2YUQpf5dvbmuxRzsXb25qYVIM3S3+bAvU6tb3/1JPaNtIyvjcHup6PnSzdbi
H3DA9ter9jvZDr9tsb3angmxaGOTQqmQlf8RaFgjbw6dy4tr6I0SyovKDGCKjHrzdrrGHepNYlSLijU5
UVUNfpROWYIiS0yiqj6KimxM0RHiiP0O4wBSNfhMC7ogXa/P8803jiCtPZibDgXp9smfIx9RHUpVDb5M
SpbhpxcTOc3PfwEdLf8HeGR3cfEefTAia/yUHos0U3jcPawQoqpKsLYn0HNrTWS0Dulm7gNN2P7+uHvY
JgdSrfrsxJXWod4UhFMrqNce99/eoP7Bz06dFEwDs3lr4nl6Ug73ss6ZL4ZxXVinL99fkVevxL8BAAD/
/w8PCvleBQAA
`,
	},

	"/topo-sort/.git/hooks/pre-rebase.sample": {
		name:    "pre-rebase.sample",
		local:   "topo-sort/.git/hooks/pre-rebase.sample",
		size:    4898,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/5xYbXPbuBH+TPyKPUltpFSUbH3otMk5HsfO3KUvyUya6U0ncRyIXIo4kwALgFZ0if97
ZxegSNtK0jnPKJGofXn2wb5B4x+Wa6WXrhRjMYZz0+ys2pQeptkMVkdHf57Tv3+Bv7VaGTiHn2UttWHZ
tyXCqLGYWlxLhyMojbkG5cC2Gn5tnYc1FsYijDbKQyfkvLTeQW6U3ogxKO/gV7Oeg9Q5ZFJDY/EGtQdf
ImSmrul5YU1NVrXSG1jvAD8pT2+3ypdiDNro9De0hmz71i326DpAmawqzFmc7RamqsyWLDTSyho9WveE
tSbHkKYs0zbOW5Q1f3BoFTrYSgeFsdcYIC1IYdUprK3UWQlrJLsh2hymxgLWjd/BtkQdHtP3HF1rLUUa
FGcdbOXAybqpEFxptg5KswVvel5Mo7Kogw58KT1IiyArizLfiTHUaDeYk84jjZ/8ow4Zs7hB7wcA57DG
TLaO9CMlyosxbE1b5WDRtZUHNQAe3UDTrivlSsyhVM4bu1sIEZ+dkFdB5oPjk9HkeCRUAR6dh9FkPIIT
WAlfohYJh3Mysli4ZYkyd8vJaiSwcth995Gyx+3qtalUllos4OcXZxcf4csXkVAiwBE8HcMWITegDaH1
aG3b+B50jl5mhJU0RaGEyKRDGE3YwwiUFgMAp6fLxzORPH0q6L9vuzC+ROsWLI1OZkKM4ZXZkiwdSo6y
6hIV5J2zu5soYgxG0/dgCqil82gXAC8dKA+v/05nGQRB+VPycWH47DGatCiriuvC+VPBhJVmy2Sl/+3j
/PIFPosEs9LAsz+uYPTKgGsJSkAUxWLMx+KWPL100UfRkos+uQLKU6GNv1L6KnwMp2XxJq2U85CmjUXv
dydGY6U0wocgtof0cZ8X6W8wmtyxNYop0uMNSlTRh8E8hTV6Mm+xNjdE1mIfTTzBjBObkx2Un8O65VZj
kaxqA41R2i84Rwax4w3agTdK8FOAlwU4AzvTEttklnJjjX3eKb8QRle7K1K4Or5Hzp6LD935TD7HErqF
L+CM9R8H6quvqPd/B9T7qhvgoPobPlh1TEf6B3W399aDDG4/iuTQyXUZFOwdPLqug7QNUZlLj6E8ukNP
fteBJaFlxHIVSaFiE4nAKNDvJueAwD5Bk2XrLM/IBm0FKcIjkST1LpYLnMDk7M1P/353dPk0Pq/dhhh+
3EmU0vEoo1nXRd8nE7vsusKT93oUzUz/MIA+gxOoZUPlmyTLD9N3R+lfZVpc/mkGS5JPppNjOHkGxzP6
dAuuqZSfLt/r5TzCO77krwpjgTBihTVM9ybv2ZwuHs8mwXDyLlierDi+g7ZXl7NZsKMKmP7AbcjBZID/
MztMn707uryNoixLXHWfk8Yq7eFfby9evHnDLAYASatzLAYPbsUD6RF0Do4vI4UsdiuSR33/Gw0hjR72
m67xUfX/+OP7i9fnVy9eXQgxHMq8UzhZ4KaVNncH53EpbxDWiFr0Y5Knb9fzt6bV+YIMI2yNvS4ou6Vz
bU0DNST3EyHgMbzWGd6fHLSCuGBwFKHP9++4LKhfCYAuy5T2hiaJ3EilYYqKCghyZTHz1Q6MBaW7T7PF
V/3u+25mDO1AtJoNPezBkGvlST7HCj3mC26W1Ck1hqxft6rKBzNP0WYDmbGEgvRR2kpR11XOy2t0c5Cg
cfsAUWZResxpLSReeEdhAzwdFRuntx24BYQdi7uHB+etYhI0ZuictDtuMTGCmjzTG5SOwHgD14gNRWK7
xQecosQItP1SIpN/J1buksZ2O1PQzkqpN5QwJoREHrssmgdaCXcdqQ0ZGwRi4rjMqoY6IieV1ICfOEXn
UEqbZyaPK0LnNnKmZY2CTgCj1dBTw3l5q26UrMJIvaYJCpnRhdq0Vq4rhBslxeSnl2+vLl6+WYZvoEaK
Rbl6IcQvYcVWbp/Wc6Yi7JNbyQssXGuzfSLE9HgGi8UCVHE/06hjMo1URINeGQAvAP5jWr0hyu7XH10h
uPycbxuV79NngMJKSn9WziqUmiZRvKlEqpTehAuJp7fDog4THjVrD3OfF8G7MNbIaVPt9rcBmnMmJBfI
osCMV/Gg2qChLAJ43nowVH3hRPYdZEAkGyAoHaEWt0rnvG+I6epbrDKh97enfW2w4bd0UyFfFEQoYLIM
8E+iSNWNsV5qX+3m93Yf1j5Q2Gl6J0ao5W4/B2ME4TS4JDrSLVZc2FQg+0VXOmikZ4q5mTnP1cTqfS90
hqLfl2DRWnYfS24emY27YnROzWPgaNqgLWXj+kujkzVy8cxAFhZdvFD5EkMehlbTUyn+gf6Rg4rmhfSh
KGKFPhEiSQDApGn63VdMetZYxk1vOdj67rwnKXog0zSl1xrODgot7z07IDN4Sq8sTdP9C54/lFwOXv3f
+weCQ7k1Qzy/Ixnllt8xuWTW/x8CeyK7OS/E2Ryec4Wf8z3tbhMJrfyM68VohEJ9AqdiSW6l6yonbLCx
J7HOc9YplOaKpannv1J1Ubcb2gQldmOKiz4qKgEqkdCru0nKfs7ZKnWA+72RUk1WFbVivNd1ww59Hu3t
fwCwWND9/yx0PNSZaa3coHj+wPFbGtB103qE6fGMkvjgheRDYJN/BUi+dWVhiXCPKNFRX/BZOYd+aR4E
qDSL9+ENwawegol36EWYrdFJGPv8e0zXBL7eCkW3/v0vAAD//4TsWFEiEwAA
`,
	},

	"/topo-sort/.git/hooks/pre-receive.sample": {
		name:    "pre-receive.sample",
		local:   "topo-sort/.git/hooks/pre-receive.sample",
		size:    544,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/3SQT4/TMBDFz55P8XAidrvQLsuRVZAQB9jLdiWyN6TKTSfy0MSO4mm7CPHdkRP+FCEu
lux5v+d5r3h2vZVwnTwVVOBdAD+5fugYPsY9UjPKoNCI3u0Zh8SILYZD8oiDSgxpRQVqz7+xJP3QfQU3
PnKC67q/1FDvFEndqDiJelxk4dY1++qCCriww8hfuNE/KCecPAeoZ9h5aM89ISnvtVtNAeoIDm7bMdRL
mkK8xMjB9T9fWsmzCDuMvBy5YTmyXRFJC+WkWAbY8sNdvXl4/PRxs36o79b3m/frx/vaknoOZKR6Rebk
J59M2FIslp3+nzO7SMbw0XWwR9cduPr8j7QUS8Y0LjFsOYksJGTsV0FXCzLzFXY62zH2Uy1nUZY58RuU
3yaL4qr6bvH2+etM3t6SMXOBs9OTKG7yD8k1ZIxU5eWl4AVuFou8cmBqhX4EAAD//5LE+JYgAgAA
`,
	},

	"/topo-sort/.git/hooks/prepare-commit-msg.sample": {
		name:    "prepare-commit-msg.sample",
		local:   "topo-sort/.git/hooks/prepare-commit-msg.sample",
		size:    1492,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/4RU3W7bNhi9np7iVBLq/JjSst2t8IA2yzoDyzLU3l0QlxI/WVwpUiOpdin68ANJK3M7
Y72TqJzD8xcXz+pG6tr1WZEVeKlBf/NhVITemHdwrZWjhzcYLY3cEnxPaM0wSA9l9hjIOb6nKitwzZUi
geYR+V76wx/l+CB9H1GaDwTTxedOqkDFPXruwklWzKwHxiU6o5T5kBgDRlBSI42eaRIkK2bQwsGZybZU
Ads+eVg4jJMdjSNIF5yQkP4kOqqqgHUijwF0XCqXPHBoo9lHsgbOcz+5ZVYcxyEdeGOsJ1HFLLcGpHkT
jUoX6ZawFGOIJykEg/yQLUtEbHD7vMoCw4yD1K2aBIWoLNHckauiy05a52E0wdJg3tMcaF7gd0XcEUh7
ssda59qqKkdPajzqMd5LcNQaLY4vJpjJj5MP4ceGhew6MBYMsZQImM2zAlJ7EwFPXf45OY+GOnNYUMQn
TH6gDcGHEA9LCJIFGmr5FJrzEIacXoRdjZQKYYwPpAWMTe/ur4m7nsTTlty/dnwvrXjaNhfCgWMj95oE
M13HmkcoqWMdnwmPG225zgo4L5VCQ3FAJOLEpAu1W25JPYJjb4yAFMSrLLu+u71db3e3m9e7n9e/3qzK
q/loc/fHm+ubVfldtvnl5dWq/D7L6snZ+H84klVgsmr4OzBNWIxWao9JK3LubKgfqq91WlfVUD8UZX2+
QF5+oSIPs2oD/OlTUrMsg5YcMjjF8pOnYVTc0/I8vAOnBY6ERfoOICnN73WOCm+PBtLytifxn6W8zQp8
A9mhfihqPH+OMg758hKrFb49JR4vXoTbLs7TAzneBj+bu1er8ixc+J5bvF5vdwm4vXmzW/9089sWn+CC
AI2Fqx/uz6qLH+/Pq4uy/mwAP+D+qh4XwXDgkiHf0ZJn3nKpyDowJjUbFW8JbD5FXm7uXuWnoi6COU/O
g338Mu88/XbEtP8n3KNMZYdnKaFdWOrl5eL0nZ3M/gkAAP//7RM2MNQFAAA=
`,
	},

	"/topo-sort/.git/hooks/push-to-checkout.sample": {
		name:    "push-to-checkout.sample",
		local:   "topo-sort/.git/hooks/push-to-checkout.sample",
		size:    2783,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/4xW3Y7bthK+jp5iYi3OWR9YXmwuk5MUSbpFctEftCnaXhk0OTKnpjgKSdlRi757MSTt
9bZbpJeSyOF8P/NR7dObLfmbaJumhdce8JMaRodgmfcQdaAxQWKYRqMSggJtUe/RdDwlSAER2IOCHSUY
p2jXTdu08MFSLAUoAvkD79HAdpZVXUCNdMBuVHp/fbuEo0UPlCCg0inKUTtKTZurgfKmnhwhYI8Bvcbr
uASSPfJu5EiJw7zKa3OxZDHvblpIgTBetC+ftkF5bSFZlaQ9PYWAPrn5hAwEmRRLFpsWar9rg35+W9a+
KRU0+552U1CJ2MNBBVJbh1IzonDWtPXY9z4mVKZw82YGg72aXFpBnLQFVaBSRjhFNEB9bvTIYU9+V1iu
DQF5g5+aFrisCThwwgsewKoIys9gqK98QR94yKvPWJv2AVrNw0DpRaFvy8l+5nwYVNKZ3/uitchK3s2g
AlbwRujP6/Nqj0c3Z8TyhcZ7KEWX9UPzJIYtQmYlMfABQyBTdKwsNi1s0aoD8RRegOUjHjCUxtggbNHx
EQKSmHpALxa733y/tWlBiIOYVEiCemTyCXoOovMBPQnGgQ31pLPiJ6vXUak+ifVo4QKOlCwcLVXsicYT
2EqaNF/MRBF2nNkuiAt3z5tS6eXVrYzn+wRayYieaivw7LvfMLA0nqZMWLHReQzg+jRihjE2LUReydMw
xQSeK6j5Ql0Of9N/uW4MIVwv4ffmCWrL8Oo/z2Bx9b9F8yS3c9v8IR1+G6S0NDmoPWYjetQYowoyYMrv
yjw+7i+uM1faECZCXmBxOG0yGCmgyXDxft4/Q+2FFasJz3aVgy8JvSCzKPwVh1MoZnMXuQViFFPNECaf
8y+gMl0G003QDfDu7vWXsLi6XWREwMGIMRlwmJw0L3t6TBdZJJXI18E+YIgIhgJqsVvTlg5PSbsSv2bo
Ry6n9hwGIeGxXkiExxjRJ1LOFbWjGlCqyIZ4JOmEQ37K4ZATXjor37J3CqUYxdUOYY84VoXAsVburHGF
8UDjXMxILortyCcMElEFVxb3PrO2mI5YxT0dum7qwJWhJpnXgQN2HDqHMYpMWm4l5aMrqZwYokXnTuZ4
m1OhafNgPxoE+cuO0n9jprlL3J3ZyMob7MlLSvsagLJsk3hjcHQ8Xy+hn3yWTEjYTuQS+ZvLa2+ti7O+
4VRJOdvqSM7J/OMn1JM49pzdFxFfPCGXXqXyvOiS7hVElqtk5gmOyudbfMRQXDJiubYi8AnGw715lzRj
1QFlqzJqTPI6lGBVWnMw5HduXgGud2txxwzKyDtYaAPr9UL8NEV5EVAUOSCMKllRknp4mr1WZrMrM999
hK6jnRdV47Qd2EwOI3RdwD5gtE2y6JsnkkWLH0cRJ9/rWSHoFTk0i6ani/Liqa6nUuXjRJj+4YTL0j9V
Ls5M52t18jGpHZqTyctJ9XcnuzHwtLMPDMj986w1gEVlNlbFjaUoJa+X8AUsJCQW8Bzuvv7uwy+bD9/f
3W1+ePf6dvPu7mfBkIdRpQwAOiyZ8uzVjcHDjZ+cq01L7ZfyrUEXsT5fXctuq6LtePsr6gRd/WXrupgM
efj/uc7yEdKqImfStNJyaT/G3pUc+K84fIzB87F/Ta3FVUnpxWXdtzw5k21ff+oeZgzndM+0SvE/AwAA
///TBgjw3woAAA==
`,
	},

	"/topo-sort/.git/hooks/update.sample": {
		name:    "update.sample",
		local:   "topo-sort/.git/hooks/update.sample",
		size:    3650,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/6xXT3PbthM9E5/iBdJYlseU5PxOv8RyJ3WmnRw602mdUyaTgciliJoCVAC0wjT97h0A
pERJjv9MkktoErv73u7bXWjwYrqQampLNmADvFGgz2K1rgil1rewmZFrB6exqHR2i1oJpbQTjnI4sbQo
jF6BlCMj1XLCBrgWVUU5Fg34UjoYykjeUboW2S3HRroSwizrFSlnX8FQocSKYEtxkeoqjw+KNgHMjQYp
sagIrpQ2ADqHoWAR3hTSf9Pg9ToXjvgkmF1rVcglGyAN/9ggWNqJqCq96RFgAwA33s9C64qEgiVnsSnJ
lWSOqW5kVWFBCH4oh1ROw5UU/BhaayudNs0E+LlBToWoK+e/N9hoNXJY0GQfS04VOXJi+QiScE6q5bdg
fBeIlc5l0TwOQvjoWInGxw5GknKIwpFBZkg4qdWkFzS4k+5h7gsjVFY+lX48TT8yBTmpJqB/GhRDK+2o
alrG92HKSclWWxHWA5CkhbQdCy/eKFpc69VKqByVVMTaHpnz4QVnusoN3c358CVnijbx+X+8M/xTFOQa
ZCVlt0wW+ID0C/jw13c3n96++4Pj42uPSLGEslKDvw35MLWKWNpmDy3tgWc9GBOOq5OXnSFOZYFG19gI
5c7DU6Zr37/1el01aAOGYN7/vjGGM1waKq5wGflc4TKSuRp3Jz9LhwtWSNaj0WaCI9XxRbTe/R2dHNGs
rVjSqweiHgft6hAmyeHgmA9P/WjLwlekqWvWNPd6+cagGbMjyT/JRd9gzA6l+piLw/N7KJxYPgOCE8vW
ejstnmS9PT32GQ2qRKENlEZOUW1SK7Y2+i/KnH81H55aypESRhd/j3bSnfbO8zHLhCXwYc+QQyrG3ysv
kLzXcvwMX8H5uNPC2dkZfo9mfQxxlZTCxgFBoe/3ZZG8fs3IimwrjkDH87ZsAFmglZ9v6dlsNptMJv6/
c0g3shChm2RYpTGpEH79TdgXMrrNZilsmepFAJem1uVS4XKa091U1VWFr3AGow+z9P8iLT6OMJqNxrE9
dtKfgw+9x14TxE+fQoViaEaVpf0PbTmFS0MmUtfRGYd+aBPedeB5FzAYh9wnhgo79RtqenYeuY5ZkgxQ
q3RvkbIksaU27lM32Ib/tE+Dwc7HvyxJWmqH7cTxYg7uTE09kkmvvjclHUU9x3Av6rkvk9Juf4dI25dO
LH/f83tLGPlE+V34AanAV6QWH0dB1mE9d1PRF3pt9FoshdtOz2QrpqSQLPGS2stbLE/MW6uSmLF+KrY9
+Wgi3nabMy7vZzB+EGVoaA/xsK59lNve30OJkxPEa+FduhbGEjpN4Qo7pb+8OvHR7ymtWGLUmYwgKkMi
b0CfpXV2ck/FfgswnpGDR0tVksgPNd5eHrYZ6BbTrhtTAT48HMnhwAP1u+5uGaKN8P0l7NDfo7RDEkc7
6Dl6+1F4443rMN/OiOx2d/263+C+Zjqy+xFcD7x+F+mziPeNalzpXfpJjVNpPQJDEP33P/mzveEUfgSF
/fsKtbpVeqPCfoIuEH8h+aFkqNg1nS7iif1xHtFtwR0svl+kkraknIUDM/ZfAAAA///Z8PwGQg4AAA==
`,
	},

	"/topo-sort/.git/index": {
		name:    "index",
		local:   "topo-sort/.git/index",
		size:    521,
		modtime: 1635022911,
		compressed: `
H4sIAAAAAAAC/3LxDHJmYGBgYmBgYEssyf+qaeu+Bky7xuQwwEHjEgSbwf+4DY93RPvSBQfEdGeZXlK5
JS7k8I2BSy89syQzPS+/KBWmEGSOjsKNKWDaQGQKdvNYXP97MN0OvMo/y1BvwYqOue9ezGz9Oo2B3cfT
2dUv2BVmjn2MD4zGbg4jc17oypl3uRNVWdVbTraGNd6sV2sqZuAMcnV08XXVy01hgLkDv3sY73zctCxK
wOXFsX9iTEr3f86oltdrNGTgKUhMzk5MT9XLKs7PQ/IfQXcxSNTzPfctvZB049PEvqdlD9pf2V7/dpKB
rygxLyU/Ny0zJ1WvpKIEbp7fvA8wGrt53B8kH1it6juaeGP29muzNgpt3PS3Ls6DgaOkOL+oRC+rmIEh
JMgVFGySDGYKBlz+h86t+8F6f+nuMwf6332qXPrEYO71Z/x9unMqnh8NWiSg9uyS5OPVx3l/AwIAAP//
PWATgwkCAAA=
`,
	},

	"/topo-sort/.git/info/exclude": {
		name:    "exclude",
		local:   "topo-sort/.git/info/exclude",
		size:    240,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/yzNMU7EMBCF4d6neJKLBUSyPRIVEhU3QBRDMk4G2Z6VZ6yQhrOjrNI9fcX7IxZxZBuS
ZDYMg/rK7Rj8O+U+85CaltdxEb9KTXo9OUR8SGWDr+Qwp+bYxFdc4gXUGJOWwtVtDBHv2kC4Nf3hyVHU
PO+Qirdn+MpImrNuUhds2vOMbwZhUZ1h7NAUIs4qbuTOrRoeej0Lx0WBJOzasdEBim5898eXEPE0fip9
HeMv/AcAAP//dz3NIfAAAAA=
`,
	},

	"/topo-sort/.git/logs/HEAD": {
		name:    "HEAD",
		local:   "topo-sort/.git/logs/HEAD",
		size:    702,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/6zPz2ojMQzH8fPmKXxfNivL/4dlaR9FI8sT03FcJk4gb19KyTWdQ3UW/L4f2HmKkw7B
MJtMhpENJ2c9eoLZk7VsiJMYSajWelf/1nqPGPBlaVTXI/f2X2lvHOiUtFW/QQP84rWfZVJl600tdZyu
8+fjtNb739Hf+59L38ZxqeOwe1pbBCDy6I3JFNOciUpxBWIILjpJJpPLIX7baPWj8ST81q9jUq3f6nn5
qm10GbKp0XcvHnan/ZwhPTXs3hldZbntBxQEDSLJItkwCwNTkFjAooXko5BDgGDccwCCjvgA9NbqmNRr
zpLVRufcmyp1lcNHAAAA//+jm0/jvgIAAA==
`,
	},

	"/topo-sort/.git/logs/refs/heads/dev": {
		name:    "dev",
		local:   "topo-sort/.git/logs/refs/heads/dev",
		size:    298,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/4zOQUoEMRBG4bVzitoL8qeSdJJBxEEFr1GdqmigMw1hNnN7N66Hfhd4Hw5GLjAgsvDi
vUouq4q0FhtySjFHK14lasq09Tu9bv2eOfH7z5C+vdR9vJFbfIQrJRR6hgOe1inX+numj2lyM6U290Hf
X5fP0+FXYziYlcAS0moVVZLlhsABZckmkYHk42MUw2X+R9V9jH4700XVlKZcdR/U+manvwAAAP//5yFs
0yoBAAA=
`,
	},

	"/topo-sort/.git/logs/refs/heads/master": {
		name:    "master",
		local:   "topo-sort/.git/logs/refs/heads/master",
		size:    164,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/4zKwa3CMAwA0PP/U/iOKE6cprhCiFVSU4KlBKMSDtkesQHv/PBHIOymiUTomki8kPAY
oo8Jl5hCEErCK63soWiHU9F+9JO/5Jq0DGL1DC7SiI7ZBdihQ/yTYo91httmFbK2+3v5xrloPzR72v5l
Wxuytv9PAAAA//+T9UsxpAAAAA==
`,
	},

	"/topo-sort/.git/logs/refs/remotes/origin/HEAD": {
		name:    "HEAD",
		local:   "topo-sort/.git/logs/refs/remotes/origin/HEAD",
		size:    164,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/4zKwa3CMAwA0PP/U/iOKE6cprhCiFVSU4KlBKMSDtkesQHv/PBHIOymiUTomki8kPAY
oo8Jl5hCEErCK63soWiHU9F+9JO/5Jq0DGL1DC7SiI7ZBdihQ/yTYo91httmFbK2+3v5xrloPzR72v5l
Wxuytv9PAAAA//+T9UsxpAAAAA==
`,
	},

	"/topo-sort/.git/logs/refs/remotes/origin/dev": {
		name:    "dev",
		local:   "topo-sort/.git/logs/refs/remotes/origin/dev",
		size:    138,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/4zAQQrCMBAF0LWeYvaC/PwmzRREvMo0TjWQYkG7yO29Qh8OkoUIcJ8iLebZC4pl1wWR
EdOobolAHpK02uXWaldmPl6r1XYtn/UuYRwSCKrKBQE47dvTfi5zl23/vs//AAAA//+yvZDNigAAAA==
`,
	},

	"/topo-sort/.git/objects/4f/c2ceaef805dfa5bbccc08feef279a5e4309dd7": {
		name:    "c2ceaef805dfa5bbccc08feef279a5e4309dd7",
		local:   "topo-sort/.git/objects/4f/c2ceaef805dfa5bbccc08feef279a5e4309dd7",
		size:    226,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/wDiAB3/eAErKUpNVTAysmAwNDAwMzFR0EvPLMlMz8svSmU4bsPjHdG+dMEBMd1ZppdU
bokLOXyDqvLxdHb1C3Zl+O/BdDvwKv8sQ70FKzrmvnsxs/XrNKiSIFdHF19XvdwUhrzQlTPvcieqsqq3
nGwNa7xZr9ZUDFVUkJicnZieqpdVnJ/H8HHTsigBlxfH/okxKd3/OaNaXq/REKquKDEvJT83LTMnVa+k
ooShnu+5b+mFpBufJvY9LXvQ/sr2+reTUJUlxflFJUDzGCQfWK3qO5p4Y/b2a7M2Cm3c9LcuzgMApKZf
GAEAAP//HoajL+IAAAA=
`,
	},

	"/topo-sort/.git/objects/7f/0ee74d75d062d8f2918ee576e087ea3dd7f6c9": {
		name:    "0ee74d75d062d8f2918ee576e087ea3dd7f6c9",
		local:   "topo-sort/.git/objects/7f/0ee74d75d062d8f2918ee576e087ea3dd7f6c9",
		size:    38,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/6pg9D510j/IwChR4+QJnTCGRS6ti47smfInpnXLmTkhrZNqGFZrc+0HBAAA///I0YLY
JgAAAA==
`,
	},

	"/topo-sort/.git/objects/f2/010ee942a47bec0ca7e8f04240968ea5200735": {
		name:    "010ee942a47bec0ca7e8f04240968ea5200735",
		local:   "topo-sort/.git/objects/f2/010ee942a47bec0ca7e8f04240968ea5200735",
		size:    155,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/wCbAGT/eAGVjkEKwjAQAD3nFXsXZLNtmgRE9Cnb7K4GmlZKPPh7+wUvcxgYmLK1VjuQ
p1PfVWG0QkVZLWEQ4zDPpRRMpmoUMwcdB8wi0b1517WDHwmReaJpGIRTnoXZLBimGEMKmg8bJCbHn/7a
dljqF64HEkW6PxvX5VK2dgM/DQEJfSI4o0d0hz3Guv6RuIeICuy8ytbA6qLuB3tFQg4BAAD//0s/2FGb
AAAA
`,
	},

	"/topo-sort/.git/objects/pack/pack-6179faab20f2d649a12fd52aab3c8d6e32b27dcd.idx": {
		name:    "pack-6179faab20f2d649a12fd52aab3c8d6e32b27dcd.idx",
		local:   "topo-sort/.git/objects/pack/pack-6179faab20f2d649a12fd52aab3c8d6e32b27dcd.idx",
		size:    2976,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/6TW+T8UCB/A8a9hXDO1auxoacwMZhTK1WwpJLcsmtaZdZNjHauZtWzrTo4tITZXTG6K
kDXyjMgYIkvaHeM+qi10kCtWxvPD4wcvr7bteZ7P6/X+Hz4bdCsPAEDA3yewjeAWQgCA3EJ4C5EPEP0I
sQ8QBwD039jxf9i56bMtJP7BLgDYvQ1mG8lNn2/CfiIpAPjivyS9SWabvdvIfgT+A4j/QA4A5D+Rwici
AQD5AxQ37dti/zZKAKAMACqbDgCA6keobVLfRmOT5haHNlE2fQkAhzcd2ULrI45+wLFttP9HOgBwfAu9
LU58hD4AGGxhKFxgNzJdr+XZNme/3zmFYa//3lNP/IC8X2BDIstAN1j5pu7RnITE6QRx7umH0csZLnKH
5Nmidg+vMb/zi9zhNUp/chd9dl7V7IfCE2ICsuWN/jubrfJKEs5xptpZOP25NZ6RjsTeXQ7ooInMd2lG
+HXn4GDSN/v+ZMhJEsRLyJpDiU0VGy6iP9g7Xx1yCv1i4mhFMsdtIIfZn12zu6Z2PcLZlCDIrnhV7x3e
z8djLZHMbOlLljqkxKYfxcIGm+Y6izaCpU0GSyJ+VyWz8j3NtEweX4t9f6aiSTILGetSR27B0tW780KY
O/CvpsrDdENv8htVflSn29mkbdiiVZaeNv8iOXP5esuxk9dL7EJWqA/7FGbqqifLma3GO3Rmf1nJE7da
EEnJt9Tc/+IoU8D9tp4ttvAAGSsd9+VGVReRqdPZFVloav22h3pY1Nv7hYyFmsTwPtajXDOzJI5EWdOx
olqypKhKu2tpeKwVxeJU5LKQRWh9VL6CoGbj0xNLonPfUpnTDknDM7zCgsvSpWefWI2I9Zh/3azOtI5x
ipdm86U9UbO4OrrJiA1DNOHwNLbN8qK+XqRuTUqW0f3nLjwXhaG+mtK4RVn+PSsRZ0eE1qprRmoD+Q+L
nNVJPPVlhfg8mayyx7XZWLunFFk8r3r3eDvO8Nwj7lds/467qqqoI0+0XlXTnUk8epSB12SgTXnWKMqN
hFS80BlnGz0YSY6hnVMbSvbPodJqvyMujiuuL2Nm7puH4K5PNkakukyuiWOKqm1z3zHifUIOq6O+HZQL
sCYx3to7ytWnnJoZDq9zKfzNX+cCqiO6NeytkKD/UtWNGKWIxkj1foKF2ox/+r75jtXXAukxjb4iPkIR
LmKoFSeOcqiNhvJZbFKXtuTSwHwb6p1BcZPPbV/EBMLv52a7Y/Pu04+zbj0LYGJLw7Q0iKYZPERRPeE0
9Xu5xQtDzielqgG3kC9+evetiwL5U71lX4eNJVdnyIYfZ8TKiEZzShQXE7vupOgfzfoO5pSKn+cV8DtZ
2gHJvyddmlJ2v5UlOF+aUs0N6/MkKZ1H/k7XHR7HXKAdqrDij6yYkXPI4+uxDXMTigXC/NYqnmzagjOD
eNK/9N2vpez7e5JWJm87mP60f4DzEzVJkUXz6b8W0D8yX/2MI7JSxBUMXnMtyxW6rDCqiZ+tlTRhWrNG
FRf/kjF+qV9E2ctc779jX9kbfzFk3Sd18UHM+arZejXZhjv56KoHP6cH7rl+mFEm+LTPApNV1PjKi6l9
LegqKRpzcO4011jF+uhLVjZXM5TdHXfXAU3RS/dpVzDsetmy0PV9gZ0KUbBt9dHC2IjJ40vyv7YekShU
CbXTttQb0RDlu88j75QEc7S/2vPEaCAqMR3ZElH3SIbmeK6yQxttbh9fzGjBHsimPFYYktqtt9wpRevW
KWxld1q7+6H8DNm38nTTusQN61+PhlmHSw+w0u9l0hNfjyl13+jwCfNajxnXvMP9irbxpW3aTsXegwnN
97r7UuMjjitjtXWOpcsrRfTXkSSnnIJjnd3Sk61n2jyScy5ODo86GHkEpiVTm71PaGXqniy5KsUYD1Qb
FXgYKXxLPdiTYJqfIDVFZL+m1JpMevUGkcZ4iLiYyD+kKPjsN1feMPODuh1mpx8Y8tpl/BePoPBvWvEe
pT7v/axpX4cY3DNnbVgVj72tLTkjYTjVzsci5MZXM8/jD0arLwaZP3+OOdhcyUT3zfSsD5cyd6HX+iwf
15SH+Kw8J8fHlqtOeRC9Hd/HjyRS38o96z3j0XeKz8gkIjktG6aIYSr3s2z1g4yyhOtvprLiln6p9HVd
7spK7Mnwq/hTa2Ex0khILXt/3MveF6+6ihWA+fnVJqJ+u4hXKgWj0bY3acwvVth0zLD1ypCOv4essTlf
hL4uRKONRjesqDTpzj1IvBpwTB1n+ptTmVtCyuHKjjRHBCmPw5Up9Qpe4r2plqqbVR1tneWdDXa6qBwd
b0N8lCvRX85d2/PXWPegRfiV42tuT9QnJFt/qHEfuMR7Fk2pYv/cP4oRYixg8by2iWUWJSrgp/Hja5xD
04N/SLj75lv15ho6ZlV8zo4Ty0M6YYP8XpQsHCjkUEmIOUxTbi/HxrhWxDcqPZVqNmVUsOdfNLE21xv0
DK/4yaQBW4pWm3bsoilKj5DlwPgWLXA/88dQ2gUA2XMAyE4A4lMAIgKAkAAgNgOA2ACQJgIgiQA4DQD5
DgBRX4CdtwGEnQHwZAA8HUCAB0DIBkDhAaRFADAYAFQPAE4EgPgOAFcEQGgD2N0KsFMLgHgKQI4LgPsG
QPIEwG4KgPAagFwlwA42AGEYQG4aQD4CgCAPIPQ9gPwSwA4rAFE+AH4VQLALQDwCAJoAiN4AAmYAkm4A
CBrAztn/fCiaBSArAIALBcD1A8iqAXzhDCDyAABtDEBsAJA9A4DvBiAEA+yKAvhMyC3sr5uE+X6zG6pc
pZvalwM1asN/C1M18B/Zn3ploth0RTMnWrq+5Dzt3wEAAP//K3r5O6ALAAA=
`,
	},

	"/topo-sort/.git/objects/pack/pack-6179faab20f2d649a12fd52aab3c8d6e32b27dcd.pack": {
		name:    "pack-6179faab20f2d649a12fd52aab3c8d6e32b27dcd.pack",
		local:   "topo-sort/.git/objects/pack/pack-6179faab20f2d649a12fd52aab3c8d6e32b27dcd.pack",
		size:    9244,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/7S4ZVjUa7g1PkPKkIKUgDAiIA3SJUMMSIcM3SHdiENJd6fE0N2iICA9dHdJI909lPK/
3Hufs//nvOd6r/fL+f5c617rvu/1/NbzU5WQUgAAAGgAAEA6DR+OeD8s5tDJhQdZWypeNaSLezme4pfT
N4Nn4AWIKKLm+x34nLDVx9W/ivD6RBcWzGZCwSD9Zf552SfFxabxhP4BRqzakKAuNxEtA6oXmrvM+Mrr
Y9s7cQF1BHxUyHjvWMnlmqKY2Ks5Fu9PJFWuQugE8AwyjnPot02SithlM2/f1U5ts+8fDORtddfKa+/i
V787wFA3zUqFYjEXhPsfr+IzkCNnG3KcbdX2v9D3QRCNVDw4IjlSAoTkIgIce0CPJOftiAVw1e8H3AXG
JW0LuwLbBIxOXuGhT47qim0hI+MBJAufsQYSdPOJXsTX6Jfqdm0tu8xooUDsZapkQ0ERwLyiHv4y2KSz
sVqUgvvZ7ujPi4Xby3r/gCBUL8c+/27N6OsCIoU1REQbBOCUf2R7fBnbHYzD6CT+Wk/w/C8ug2Kgf5p3
YvgogR36Kmmi/FrWAV3ubYDIxdUw6ffmtQ4BAp7RFhwUhF2ALRXaSKJbbzolMdcACStlQo2EtoQwWexp
R3ODdti+phrnkgFzk3MK+d8kJwxmny4StnEY+YrlSyB/1WxaZO61LokSy8Ciea4H5ToyP+j1fBYPCwxn
chPf4hNkTsX/w0aCAElHBBkXKzZ2nGjHSwZz9ySj/Ex05fQW6GS8vLwwBXxPE1bKwraAQS/x5VK/4qc0
k1PTzfO8eqfYAZS8yPumvTnPi+qLYcdpeE1CCepIy4r+tPGlpt8sW7SrYr1JbKZs+8v+4GM0wnrncIsj
uEHVD+FI6aCQi35ts6lcBWul39pTLd6XZB4R+TtyV6O65+VvxSfzxcX+6lSUBKiTjghw3Ir0knCfniaV
39Xid54E1TB3PLu9uw023OLi4lGG6U0Si5loFKXHo1sjiXWYyyq4MWe+OKnzOgpd8rHJENIleINyQZ8K
I+yo7NuFSBJTrLfDo717zgUPl1uvhDte393lKywseV4s3Bsbj2DOGwKAQ7Ut0bm+L7CohbjEXaYFWuOJ
4Yjk6BqHLjoiaa9W07s3KdwUZMzChXLOBkni2sZCekA78FHe3V0cy/t05uXJoYsevPHeBuGWpxZz7H3l
F/3a7MmuJdoklMUFhTqIqQb3ExtoBDgXaqYUgZWpKEzHMUPieiYznCAG+o46tIpDMTXHUHz0aCL9cf4k
xgUoxEFUCXtq+E5o1HTsC2rkoSSM0GHXKtjGeGdF0SiRKFs/Brtz9fgJ/6Okr8VcQ3WIw9mglmCvIqx4
lap4WzhShm+rZXn1Xg/RRahbpjOaQfDHDApVSC48AEooGPWmr07hNbGnJxOAn7rd3q4kh10+UNWRkNp/
mE2Gp64EzbJug50Raj1MIYU0r3z1dqJ9AtNONLwx9EkmS1/9xKKeHcnNVPzoOyEXcnxS5ke5Aof9/V8N
t9FQJsG/sOPRfhnJUB4tfHz2kGNNdWXSG24SiJ93N+dcAvPVXvRQa9j93s7FDmPotHMa9/RWKn4lXjt1
SZfPoYfCkv0iq/1/UH2pvNjw5pEz2vKCE4DJOSePNmlrt7S+WMuYJ5JSqbyMiIbYeSPGdGDeOfc5BbPV
C6YNEcV4hZGO5sK9xXad/UTy8SdSxssKamwUb+zJb1689Hl+Od9n5MVB2mMSeB6zXNP0mpGyx0y3CJcu
l3DxJmvVeFz364K1lVKb9pAPDL77DclVrcTQqb6ae7jt+7tyUM92weHVricvLZRTVjPrD9eYP9v6RBqV
tX6MC23reZk0oXABMPolF0wRyBe53DpB5cbDI5pq4mmGZY1TLAS96rBxVOKNRFDfhrcUxONxjD+l75aI
RhEkcOV+MxcS3Jbi1T2v4FIdq+gn3BH12sbI/AWjsrtBrwcTWHpXBJ+5R9ctSlAWVr4H4esXJKjj6boc
38tCRWOlM3NP+dkkquNQKyOtaMXJK0T7Qsrkwl3k87wyCfF/OV4JhA7Gg6y1FDsZvZTJd85JMmRQflXJ
5atdPLbwoWpsWM/7xPNtnWIgq/JzfDQcnwvFbihOkERhHwaYPtjv3XaRbX0uHSGSmbiQWZYi0k92M6Cb
+UTV6iIVQfH61tbWvcrISyRR7KbXdU3YqNe+UQ/yiJlBcd6QWtBS2cDm+LbXNMagofyXldesPZ948bgo
Ih3/r0H/sToElYX0yY3Kj8GS36X0DFTr5Y9T4S6KWxDQ2tlif3Z8yZi3RCTkhU79tibcQPLFTzrTEel2
cJKVQZ2hT0P/xKXO1+EemJFp9wHd9CrbncZLl0KgKiBO+3R5xXZyEr6zEB4GpK1O691Nn72piuZJCcPT
9QGi5yiLxLYM0kZ6DjR/hB4PPtf5Fr2Qe64r/QtwLy1+m/TH+1HcDuhgIqiXssT2c3lkOxLyRKcRQsDd
PnQkb2hmor9xxQgliNsif2hDyVrOyOF54KbI42ElOLFJjosoJtNbJopyaTLtyWRWSy2o4mHoUyclUEjJ
vJVocCoI6ueWGUCm/YZXjVg20UmdQAO0jRrzasZlI9XJIdsSxMyeUZXvfeZ9L7ajGn9UX+b8OtP84Tzz
2Q+3o9jqMhJoNmUX64P3OzSvtbG6wrXYdv5iN+duSuV7uCGqRuys+oo7dlm2qW7Wa19KDIhmqeWb9s/4
kVxEkDUf5fgW1XdFN9YQ6Y4jN3pPv5o0q5yawi6oY/WzjsOfXu8fjxNlRo9T5Xr5dTRKJymeZOkFEgHU
BBfn8W22oIYw+h/ZCmi5Cq/jalLVa9fH6XVEVJlS/N+cNr0uhmafldWbGYqc1fo+GTHjUbQoHjfe11cw
v8AigvjY9tcN0EZ+H44v31HwFcy6K5IurNoX5aOlnBcD/L2fciA0biLI+B+CdHJlr3jD4Mny6oX+WWHW
HQsLWk7n5IS/d4bSGwVZgS9DXjDE9T56ZgrpixIif/zkLHlaOXM296sJ27K0XNA0VZimC1dSkSkXLLQO
TdtEzS1qduZysfXWnbFx59lo8A9v9gWXWTL2oFUmxVvTCu69qcLoDl+2vTlW/Bnao+NvlXvYftpiEwlk
f8ytZNPNhReEeh18FWwsckqbpO7pd+QJ6E4hecvkIQjaXGodac1wwBrmon3qIL26LUQlMKKjpwTeJeKa
MJ88SIJuIylkKqc3utGpDvHk0+jyh18EjnLs9JcgEsHFiIke6cP+nCnd1e798ZwUpmb30x+7KItO9VC4
nWMOI5+u7b3VKpSFGapSj1R8gHTNysWVEJMgohQXWrgMKg9wk1qkUBLWYKukqrkluq7tDifDQ8IvCL/P
1LIBCY9yq1cIn63+NIWEyMNfncjHDcaQrvNoBhSumQU3qN+3Zv9K0jU5Sl6m6eLEDnUkyfo3LEFRQtAr
yTS5CV70556Yjlz9irVj2szOa4fDpBudeqLLx6Fl0RAeE2UO+UeSjQnPZyj5eNC1tte1O8yXvXfKFw5K
JU3YmS1Aatzx1xYFOM2eHXQ74YIUvy+2P87Z//pxDnGJbHr9tHpB48q9hmKsd8efzAsNg6vzW92HXz9N
HZ5fVbEpMZ2jP4oVzo4n+C8xJbUlnJKCwso06tMJQMpf3k5Bymnt8JB08b5b4feOUKDlWQG3i2IiNwLB
p/zZilyfl/EsiOBrQQnBrgetcaKUESi/rj+0D1hsykaslqSoSR6aSyfLkH1qQzNzG7yQZtzswZYxdSlc
f0jww8Z05jWRvip92dt6YZnfZmqj9P19qp9aLvG+MAmafxx0mTBMvwXey0mAsgn/uSO48TC8WiR9AIFJ
LyMwAto9IrryD9C93Z1ScB9ez24ArYu0h0YWl8zQ++ckMCp5ld/HldRlkb7cLNIFGkNs1ooPP2aPG4R4
VQvDU0kv12wkazXMDuwCv0B6T7c/TayWKFRV9clsIJMe7fUtq0kkR+S6WlV7+Bycfmv9uQ2U48vk1NNz
ZPKyM3qMw8NjxXKKTkRHvf9tZPehIejYQsju/G5SZY3civqNVTzoTz+HQWhgIsBqkwo3ik6GxhfLdPfp
BXF+OYMVbiTN1SGuZ0AVrbcrJ2aUSlo5k+ngE81O8I/0zLACGAnPdysDpYINsewFApR7e2E9fbpxVSy4
Mvucn2ysoBJFgYbE4cu73bNyTRGP+N7yw25i7cM0du0Uh8XfdSVAaNx4kHEflT/mFpmUjuuo7A3jm5bc
byciX14Gqqxucb4WXRmCHI6YF2tP2kXEMw5DG8/sNTlKicKtSPNzHH2rqC6u/M+fhVNzxuZW0g4Kk+WE
q4+8DF/zC6K4Eklv+iWBvJxutg7Nxjd6fcr5sQMER5BG/rU9gONm02NGDHlcXu4e8hJyWoAb2IoZnwi/
rd6Q0TW1/yq4yp80kT/yXNe6tMCoIKuRNnMm8AvWuB4zhWy53L5IwCBzt0w6zomJW8F9NRC3oqbzpr0G
fzZOUX933NAvVv8NX7hOe7hzzyMPzSCBK5BzOf4w2rxUu/uDQ2zCB7bKFUWkfD9hjMIr+hFsOIIhcvDP
Vxhw/BF6hCnnbRykfsv6NFBb89sT5oOV4xTDEKGhg8vCL5C8T3Rde5J2Q31C2FEBcrZWb/hutBNZhyt+
VtLdIczSYMLe4zKR4oe3/vbUTm3tHI2W2RZ2Vza0EH9R14EuJylJ3q22TG41eqq/ayqA0MFEmKisPBRw
N1YGHbzBorwfZmIuGeff6IM3LxqRt9zaHEGgqg99exLuY2whqVa/fFbbaP4e7KqR0p3h3Iq7s+xF9a4A
hK3ruBta521sy7S4LU1wXyFWNzxyBdx4YxrlAm2gAz89b/MBwkXpe/6u+h8p3vQYc97AgE9Vvi3PnT7l
jXy85MeVpL+Ubpa+l+zXDUza2SPu/C6YIr2hrfXkYxihfndTRffQz0JVFPctL4/AdRw0Utz+NqSS1kks
XvCsJXpRwOubAJ0KRyHUOwCXOI/74RBX/iU9tBYDDhwcVJGLHh1WYR6WY9+aYO1nX51gVWbjmFFSVhx5
syk/wKnCHqEyMsreN6owzMq8xSLHzjEuS44JcOR4ymgLgSNcT9NXkT2FhZ8SswkAj4PQ8dsk4QgDdYXY
H1xErXdaUYKH8uNXuVmePOE6FSGCLkPqMWDuLliYml3ENSoT56CcmDj91Ls6LXUEKf+0z8As1HgNGCnb
o+77PeZoDAq3erZ2N+so7rQ+oG3dm4/bcQPU9xuJcf8Q3KlNOP4N50DWtuM4d3fv1Jgk7NneGohJBAvj
2qBiaTUEfWqMTryzfw6sdHIHL5WN7GSfAl/3TPdhVzqOyIp0CScsL1/yt0tJd37di0kVU35eWem1hZVT
P8vU0DB34xo0HiL4PUSQ2ElqMlvv7OR2sSm/iZXIG0RDkZCFzkiXjUPts3914VisXXxe9SFXIee9dIuI
rB2WjbKI4stecnHJzz6jcR25x8z7TU3WIRXZVrmnrXmQTIXt2OzEhvarbWeInIiJbixrxpOHOUb10B5U
6/Gv4Dy+j1Y0DCBxSp5rjeN7IxGLxiW3k8eVy2xjQOVjrRbx4Kojr7n5O6Qq+ayebxhPgncYHK6Fcjr7
WYDyHWKaMgKVTCHtGsjoWF/Wecan9Rn3sFZY4tgV6JTVARFjzVx6qrir3WQf+58rQO456kpYVNP7YWkK
/mI6BTfCid08Q4+1Xt57M3ysf2PzJG41Uz4iok9TsliB7UZ/a8KO5FtcEd1I8ER77saPPrdMV/xN3U9l
xC+zwfbgyGAZ0hriYA9J2IE/vAOtjGHUNcHUO/qI7yZQI1mPPfsTVgrLKAb/NlrmqQeHgzoFy3CjPkPc
KakvGYk8OPIdr7srdkZhDtmu832hTFmAaUEZ19NBjLc251hLffIv2usqrMC4lZo4+e+fSyq9CGPtig7W
xM/mCKDXqGY9lXmUtirkAsMoCqvuhA/7tqC/rS/DhSN4eLm4eLjVxhRG2foVRwc55S0EHTp/0oy3unUA
uZd0ij5pOITjCnnzBJWcnbq5X+K6W1wfd7iJnLA8sEm1YLIKb7V6cX+93OctSaDTkiU30mpZfBLSPJbM
c+zCVPalrB5hh2/brFM9o4EH04hLRWSmZpV9giGye8cKYPXlyyfpAdUd5Qjmp9kxD96DgphlVQWCbSUY
JRESZ/7TZa354QLvHNv4bfPHepR899dFARg3cuY1eHAgLOav6x6KEoO2Q1k0tgHrlPolrI/TrSOjwg5r
d+E+k6C8DMnfvruDoJFgBwkd2+NaVWcP+QqyAacI5mdm7+akCFwzXcb6EuwjghqWS5WdMzA8QmY/SCnM
n7N7VMePtWPKeoyvXbadt9h2cXLhOZUgWAIFzBGUTXvg9NH64fkXLrWe6MX3Ij5bGH74cIRI33XguLIO
uFaQWyx5sL62QRrM2SYN5maAgrmr1cHVvEyysrm8nAx87DycfFBw2xswX31OgXpuQ8FLHk6aEn4GmOPz
Ow6A5Rkl+5dncKCSmpJCFxdRy3E1haf6mAa5tI70xY4EpycJIXemveykYmoBh8Vpm4jc+0viBFQCinu+
GpBuLGvHP2Ye452u7eKqvqqSJE0Ncn3HMXQT4J6KUB0SHyKJHqefG+uYKcK7FDTt+7YIWJZUu1xM/Pos
QjB4uZ1eKvSxVGjHY0b0D6tvFjcqIZz8BJ/pj8GESBFS7CcmamyEvig0W7KczxZfpanYp2sb51JRtTm0
gsfa3wvEDGtTyMqxkqc6c6uPHqC/CgmZt2Vo22Y65pgJ2Sw4st41zGza+DS2Hk6vUPX+xKfGF+pVWtA9
NDdLFyW7h+O8oBBSe5cGM22THnCtMBqbfOWNzxPOSQZlLk161Xmhaa7LZ0foazFAQnpTNi4qhFcqL7Yo
LlBePS0gtpFsvwH054AjvLq8IzwChMtzs/yzOmRo2Hv6PaIYABKbmD/qa4BwYIumkuOCIFHLnZZiDfZ8
KWsh++dQjO4qwnmoP7TJKsJQ3UxCwSyyVBr0AtZrf7aCwmcWcn991dCq/TSh8wZ+HP1lmedm1Y3yy3n/
h82dr4cHhe/9l8e/C1iMzShaijNJQ/2jZ7iD0/svDiNo5vms3/7QzMB3rjPhTGlwYL0SUg7WvdOnIvxA
qzWrH9LsVoGmorTC+/V8A8Uj+vEnzXvNjFXmuZ2fTTaeV/mxmu9Hbxoyar/tUY3cFEltuMymdt+YqyMQ
ijtBZLBkSYSu7EDXttAuX6HtG69XM83qI6VLePHZY8eZLmWF2VpMgyIVMEXaCoktJSn+Qpda1kIBu8sX
QjpJyO78LE02aASlS/AT5w+rKUR4AotfNirx7TRYzOzaf6+x2Fk1fY40eEUVXpEatbuZ+bUjxKC3UfIj
NnsifHt3b07M4xOS7UWb/t21ePQM5S/+LriM1vgX6XnTzrpxiXKZBwiXU5xclOwhh71jwAXlTlzU4LLQ
BvGHt5Wimc+yBYOkm23DU2Wi8EIW9IRp/Gq4ptUerzkrl9PAmjV9SHYuzY65/b3tl4JZ9nefIRk1157F
am1dbzFEONH2nm3aCufPEncbtE4UpQ/8wIOL+f10vm/fNqagPsT3sFYqRWoffNU4OO9fEhNcqTdA8ydu
xQnfI/r+Nc840fFSYMm5EOawVBRXL/ljZS6aA3Yei73uX2FENtwjTLNHFiWUGzu5wFnP6cjpYHnm7kyC
yHPR4t9RHd4U8M8jXFQrF+Cjs/Shg7LmVGN20t+Kn6aPDySM9miP2W537E1s623aXj+a2dC/7P6snpS1
0npTJ+jTNA1Fr0LF+JzKzbed3G/xHpe9N48yq6AgYg0ginrcAmR+etjpepLCS3gqJj/BgM38CY3ZbNs6
8unqKQVF3vPnDkg/1hyvWK1G4t2MHOl8iJaubf7ThH0iNbRJpwZKguLJWZ+KtAOKmU3nFyO07UOrIyYr
6GTSbUItRj/BY0+py7a+UK0PCBCPz1VEiPCTfv+cQbsjCXIYFX5JLoINZibtoj4D/1BjfcvXBzAPp/FV
JdzAW0e+CXGU7Aq4Rrd/rmhhYt4JoW6JoSZip/V/OKLJJCivycH9GpmmZpHLl6A7wChsNuDEm5EvsQOr
bD3vLLtGcHQf2A9K1CsupA9LiEuXvielfF4zUB3gjpX2xrqvoL2g5ezcY/ZOeIsEG78hKlkk9+TbDL6K
zzIXRH8yMlARgxErs8d6QSk0cHiVBQdgYldgKh3DieILc36xYIZpg1owrWFJkQgLwXGDva8cUBPwcV+s
mCp/RB4MKsZZSEDTVd6Wqhq3mMWWUKNqsuwPfOqMVexCt6VVfZVsA/bF1ilmJzp9aAt1ufS9UuPHa7EL
/Rgml075EIspnN7zmj6XE4eXLd/wmn3j8U3iWpAa1hJp3l0r2/wdX8idA90Mmk88uqTtWd1hxp713Mip
ULzfw5A3dRv7x89fJ7ikk/sItmIUtSqhqrnfINLqNENvKxwRe3tMjZwQpYTWh9ofTtcNfL4iCzW4TYRl
Fm1M9hXUXESxopj3qiJNwdR2u5JT5unsaHyQEsV5t9GWp9A1iME9pQ+fkZIM52TK/VMjp0m8FErF6web
396v/Ml1opgSnCmwldLDEjQppgwDKMXfB0WMcxgJTypKyFV9gX0T5a/Oa/S24sjXEePVih1y4Xa4JVd4
+0llCzfMB46AxXCDkJAn0jXhHUj5gyBm0henRJqGYO2uA5Uz8F3bgQMGK2E8klUb9KyTNayu16nGdcCj
06zqfPugVSFESx1v0s0rjY5xFGzzCG3FZoWS+lFMRVZfjrtNh3qphTWkCKzxQ8GPPVY74jdPrPqIJk3l
jGrpI+r2Gl7GsoDntUHphQer05ivcN0OpK68TEryIc7I12anwQehw9e/Ggqzx8mf44rTOvoxwxEi7F9k
zaWYmFzdbTY35hFUAG5TLIYN7adwhI+GkuMkhAiWQZz+JgyXdN0LImmfPKXE8ILAAQJTK4ygL/MMc5mb
+wmPbKGa30/xK6P2lNUgoxY8pdpJpg3oMlolpOMYOvqhrA6Escw38TguN3v8dBR4vXx/8rsq7jXyjUuu
uiqxRpjTUB6eP8dIG/VMQfu5UXZ1l07Z6vokcgJZgPO5EUcEiS03Hk7QVYvPBEZJUkR19PpZxAfE0dDb
Acmzohop0G6l7AIV/bAZsbWT6M57/RwF/d9StxQ9QqQOMfgz8eRSl1H1mR/2c9OHOfRittrLizyOyAUZ
WNVd34pEoI2B0b6n6Mailu631yeb34p438gzDvAKKc69dDP+xGRIptbgUZwhnQUg8ZOTVFRpACnVaoVQ
SueRv2ESL6fRXzTUNUglmtUG9anXRqt5jGA95sdldNvir7R7HoldkIZHR8LsLLEiKfyZVnW7/a2n1gkZ
Cc7QK+ha/a6/A5usp/FbSTfNYinGewSfAw2sxGAniQ8lOBwBjZf4GcA68nxHfwI+IDlL+Ob0S9mv4U/U
wfYs9QlG1SvzRaAmTwiWoRx09eFgQrF4mkVl6d75l926GfcNyxxes333E/OCJ1hhaAeVmPNzJZD0LUik
LY/pazzcOxw5d+r4gJfNzhmAA27KJdxxL6UIkeH3mcOBfEsVJF/VVC5wqShVTS37wqd5H5wvP/62c/bI
szA1raAqKDLrPEnIqX2cz4Z/KGb/CSOdluXOwUfFgdGtu1mVCTM8yhKhQzT2G+w7KWi5oyQ/SC7hyf7u
WwCH5afcoPBtiQtdDdS73N72e/otcPTEznV9VdZ+0qLBR2djF5WM25Ufdith8WOGTHDroynJnN+O6wOd
rCRKMmqg/GrkDK+VcN9epMnFF9KhMhAz/9DeUOKM6YQfqzJhUy0NT3ZEmTS5p0+9zPZN3W1LSylrwxuv
74q+HLCH5NKYZ1fpMTqcMLE60KYRVWwVmdoNqidw7+aD2Tbhj+RhkSNgCjYcsdDdEOksmfjm5GPnIVip
5lA99EGu0Knt05L6+kfLdV5SQG8ZvtYRkPXfk4cp192WrnZ6DbECz8ru+5CI8/dLyPBJDcB0EYHCKjBR
7k80ug/7Nxpl2kcBOGowHx0BneEI4DPA2sN34HdgXMAT4zYZ0ZFizMIzzkbxHhppl7Fpxc74lBejTQQE
m2hJj/+KWGkeAfz5HdKZuHny3TdQBnlheYYbzBuhm920/nAheeFEUgpCIOBWAB/zCOin8p8k+9KCe3lY
3j7wLwkse08XX7fpzL14ffmH5I4SQdQ6WpLDX+Ap/4C7Sgr/ARf+/0ELJ5JSEqIBFj/gZR0Bdf8F7lUa
zMPQN6S+Y+opcHvYjrLxaJHp/AM8H4xf7aADR4gM/oFl/BqetSaTGRwFeKGG4ViGCwf+b7x4igzSDijZ
3p8iFsVNY220gp5aF4dLkJK+YLRkKiresyDd3uYWDApnn4GRJNrw3bUdJa27LyQW75FLTSc/2SZPBsC4
F0d5Ggbh37Pso01MIgJ67wlOySNCgSA3Ka9jdD9eOAIoDmj/Z1yCF44KW1skHG2V9XjjeyO/ForrH+Nx
c3Hx8/LSubk6urhx2LgC1Op3dSIW9mbz86KfFr9bV1nEGVEYdn1Wd4jh7/qnN6LZHgGM+f3S7I3h/jMu
yf1CpaBdaDgmJWgzTUgIxEAJvdkEhXuASqHQGyhJbKMymZkisdpndVX5UTa1iTV1AFrhRB41Q3C/QdQI
YOsTBfQnmjYckTEq+unPJNdkaChlwKyYhRdDxAw0HJh0qizsA2rp1J07eIBMoUdZ+8AAbDgCSAXY+FtS
0ZP/iW5nFoHOMXoA938VfzeuPFFT6m51vcUYGljKuWMGttT77+IJ2lSyisJcund6mmkkT+5moWJE1J/Z
qLft/Hz+IvmX9lOZSnUZAEUneqDlJyY4IoODX8KtE4MDgAtCyzwCfvjXZyOnmbe3i2SxbCt2L8PfthhO
rCJunf44sk8e/4Odv+q/kON/Q7aiB+wDJf4BQL6KlyJDi3zPgrS/pz6icL5XuO367qEDBqSU4docowcR
/Vd57jSZa98/xhut3YFICj5rIlA5oVb/XV5z+jQPvHMouFEHjw+SZNXzQnpgP1GSusYuQP9fLmt/c2lE
9z/ESMP6S5+CuRQBlauDaceW5LfGqAwtpz6eV7K9uipbJjxEmrV1MK6xii11QODGwAZiqv/DfBdT2ybe
ppbWWEgYwPq9WHC/nL4nwAJG6nkE9DP4j/YkPZqdzpmMXinqYU17Sbv1SFzMx0tC81eXKC2ghxGf1zqL
48/7uCHbOeChyw8NQLyD/vV/yYRYVeUSxVRtStFar9ReDz3+6Hl7FVDhWZIX0LVx0HWh0VKxfi8a8mq+
kfDDtFKU73WGArw/5LPQCnmtJeQ/XXiQ9n66Yf0kbSYzXrSI4O2rmNIGhCc+wFxYrmEf6Mf//zJSaz/D
P8cEk50l27vUtQCPi9B9CnH+px8tY6Wv2HAIMy/Eo2S393/+mpQ2vBwRM36ktvlz92CP/GDgZCVw130V
9lsnxBNX023IB2X6bn/WWpUBM7x/Pny31FOn+8YDTyF7WO/ieONZxmLroIEYZ23izJD5bwyYljrCSANN
o/uz5QzsZ0Snpe4HmbNUYcV+waJ1lz0+wAdRcZJD9ECOP+vS7G+N5PxaEjXVfDGgiJmtiJmBGJLHpXel
D71Y7Bqibtm41xf5Y2LMQsTQxlTzugYDKyaD0SgRQ5UuByDqkoQ4H+0/1Z38X4cF6CMliLfyx4MjMga0
eSU+mPqxAvB90Q5MPG7L6c5m5HI5p1nKRaMdXn3xGf7/AgAA//8w3GTDHCQAAA==
`,
	},

	"/topo-sort/.git/packed-refs": {
		name:    "packed-refs",
		local:   "topo-sort/.git/packed-refs",
		size:    514,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/1zRS45TQQyF4fldxZUYd1LlR9nFYiL5VU1EmrSSAGL3KIIB9NCT/5N1Pu3vFl9fbrXu
+8/z48vn/b3qUrmv75fLr5e/x/16e1TuW8wughGYhgGBMZkGDGs+jCjQYhbWhP3ZO97q7fqo+/F6O7+e
vx3f7P6o2xbWjMhHZaZMJsluqR6TvKYK6azMAvvTeNjr/fijHejQt5Mjq2UsFR0yVg6dfVGogrhVLR/Y
erlutniSSsBMDZbgrgbiITg0x5SROTIW/G/woW2nYAyKrgXEqdp0TmocTcopW3dBdgHLbXJKAyMf0Bi4
CwMsUkrjIuvirbWeCz8afTtFWxgmbMACAb1h0JrZFmZlkCRoADpvAtjStEZM5y7oIA36olwgK9foWBad
/F+jH9rzD7eKwS4YU8aaCKy9I9RqDPlcLZjQyrffAQAA//+zwyDJAgIAAA==
`,
	},

	"/topo-sort/.git/refs/heads/dev": {
		name:    "dev",
		local:   "topo-sort/.git/refs/heads/dev",
		size:    41,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/wTAURWAUAgD0H/TzLknEAc5o38E7xI37BJb8XkwHc6FKNSb7kMgnnP9AQAA//+T75Gm
KQAAAA==
`,
	},

	"/topo-sort/.git/refs/heads/master": {
		name:    "master",
		local:   "topo-sort/.git/refs/heads/master",
		size:    41,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/wTAURWAMAxD0X/UQFO6EznhMf8WdvGzlkB/RCH89tTk/ibdKHhru64TAAD//5WGkGcp
AAAA
`,
	},

	"/topo-sort/.git/refs/remotes/origin/HEAD": {
		name:    "HEAD",
		local:   "topo-sort/.git/refs/remotes/origin/HEAD",
		size:    32,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/ypKTbNSKEpNK9YvSs3NL0kt1s8vykzPzNPPTSwuSS3iAgQAAP//1iXUoCAAAAA=
`,
	},

	"/topo-sort/.git/refs/remotes/origin/dev": {
		name:    "dev",
		local:   "topo-sort/.git/refs/remotes/origin/dev",
		size:    41,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/wTAURWAUAgD0H/TzLknEAc5o38E7xI37BJb8XkwHc6FKNSb7kMgnnP9AQAA//+T75Gm
KQAAAA==
`,
	},

	"/topo-sort/.gitignore": {
		name:    ".gitignore",
		local:   "topo-sort/.gitignore",
		size:    79,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/8rLT0mNz81PKc1JLebl0ivJLeDl0itOLC7WTU5Mzkjl5UrKL08tik/Ozy3Iz0vNKynm
5SpJLS7RxxTW0svJTwcEAAD//9cMJTpPAAAA
`,
	},

	"/topo-sort/LICENSE": {
		name:    "LICENSE",
		local:   "topo-sort/LICENSE",
		size:    1093,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/1xRzY6jOBC+I/EOn/rULaHZH+1pb25wGmvBjowz2RwJOI1XBEfY2VbeflVOemZnTghX
1fdrJotWGDRusEuweG6FecmzPCv95ba69ynieXjB77/+9gcad6PJ1q5nF4LzC1zAZFd7vOF97ZdoxwKn
1Vr4E4apX99tgejRLzdc7Br8An+MvVvc8o4eg7/c8syfECcXEPwpfvSrRb+M6EPwg+ujHTH64Xq2S+wj
EZ7cbAOe42Tx1D0unl4Sy2j7Oc/cAhp+zvDh4uSvEasNcXUDgRRwyzBfR1LxOZ7d2T0o6DwZD3kWPa7B
FklqgbMf3Ym+Njm7XI+zC1OB0RH28RptgUCPKcqCnPziVwQ7z3k2+IuzAcnud31pidRfKNT4iCnQy8fk
zz96cSHPTtd1cWGy6Wj0CD5x/mOHSC+0f/Lz7D/I3eCX0ZGp8CcVR133R/+vTX7u5S4+uuEeeqrh8r3c
xyhM/TzjaB+p2RFuQf9/SyspCLFfoutnXPyaKH+2+iVJqDk6tTF7pjlEh61WX0XFKzyxDqJ7KrAXplY7
gz3TmklzgNqAyQP+ErIqwP/eat51UDrPRLttBK8KCFk2u0rIN7zuDKQyaEQrDK9gFIjxgSV4R2gt12XN
pGGvohHmUOTZRhhJqBulwbBl2ohy1zCN7U5vVcfBZAWppJAbLeQbb7k0XyAkpAL/yqVBV7OmIa48YztT
K00SUartQYu32qBWTcV1h1eORrDXht+55AFlw0RboGIte+PpSpma6zyjvbtA7GtOb8TIJFhphJLkpFTS
aFaaAkZp8+12LzpegGnRUSYbrdoizyhTtaEdIelQ8jsM5Y0falE6/e86/g0RFWeNkG8dHSeXn9up1f8C
AAD//3+mZMpFBAAA
`,
	},

	"/topo-sort/README.md": {
		name:    "README.md",
		local:   "topo-sort/README.md",
		size:    259,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/1zNQUoEMRCF4X0gd3jgIi3EngPIHEFcqCsRUtMVh5Y2FSuVkbm9TDcKzvr/Hu8GL42O
2buH3gxFDMQMKmeUviwRvXB+n0tmiCJ/Vjujmc7liCKcR+9SSh90ojbpXM27EymepcqTqGEPzV991jwE
kyp3TdTC7b13m7O2oZK//zbDJa9hJOYhUIh4DYcQEabwdhV5jRfyT+x2eOxWu4EjxSketrsF++1ybL9H
KSXvfgIAAP//bdVKJgMBAAA=
`,
	},

	"/topo-sort/package.json": {
		name:    "package.json",
		local:   "topo-sort/package.json",
		size:    476,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/0yRwUvsMBDG7wv7Pww5vQd96XMRlCKiRw960Zt4iOlsO5pmwiS1lGX/d5luWT3mm29+
38fksN0AmOgGNA2Ywon/ZZZiqkX/QsnEUUf/7aW9WOUWsxdKZR0905ACgost7F0usDwHjMWpA3gPyg3c
kXcBFE+xs/DE0GLC2GL0hNnCPXgSPwYn0IlLPUwUApReeAIXAUVYYKLS//git5iB4p7t2m1wtJQqmmM/
8ip/4jyxtNk08KoCgFkyKrVVv/pV506zUePbad+NpWdRcKAZbgLN17ur3V03OArW83ALf/pSUlPXjsS7
lMeAqv9d8wUTZyoss2ngsDYoc1rO3tF6cAAzSlBJYbmp645KP74rqQ401+cPsrqjK8cTP5DHmBfa48OL
2W6O2813AAAA//8Smx3s3AEAAA==
`,
	},

	"/topo-sort/randomfile.txt": {
		name:    "randomfile.txt",
		local:   "topo-sort/randomfile.txt",
		size:    24,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/yrJyCxWyCxWSFQoSsxLyc9VSMvMSVUoyQcEAAD//381w9wYAAAA
`,
	},

	"/topo-sort/tsort.js": {
		name:    "tsort.js",
		local:   "topo-sort/tsort.js",
		size:    3056,
		modtime: 1635020789,
		compressed: `
H4sIAAAAAAAC/5xWW2/bRhN9F6D/MMH3IMmSSTsBvgergmsEbRGgaIEkb45QrJZDcZ3lLLE7tKI4+u/F
7pLixXYLFDBg7WVuZ+ec4ax2CI6tkjxbTyePwsJnU5lPxjJsIK9JsjI0XzxNJwBpCo6NReACgepyhxZM
DoqkKRXtAbM9Or8Tzk2GLvFmXCiXKHKwgT93Dyg5kRYF45xqrRfrxvPnAuErHoMdVEYRO2ATXD0KXTcO
z/5KUb3q7zSdlCarNSb4rTKWfeS2qvV0Mp2kFxfTCVzAXZbFpOfGgiEMixWoPIZ0oByQoUthrTgukmDz
cyWsKOHp/mJ7isn+YQh8aDAxm+G1mGJz14UyDRdom/UOPXKhXsyAzQoUYwnGAmos0aOgCBRDWTsGMgw7
bKJZwLLiY3g+2oew6XTSFppU1rDhY4WJyLL+Y/rAqxg+vmvMZAN3vsxEufB/Hi/AbXN8A/fhxzYgGJ5M
kWIltPoeH2fmxq0gTU0Bj/aBZW0tEkfcCuHgamgy6JcQbwub8caPH3DVJXFHWR/QFRwKJQvYHSHDXNSa
oRCPCNfDQCsPn8pjIkJbFNkR8Jty7O9ZFA5B8aigXj25sXNPFrW5WoP6KTa7RtpzsYblUkVgAfwdgk3M
7V5t13G7q2hY3xZu+6vlNdzAdbA5xYLb3h9i023cjjYSaUgKbh/zJibiOTIgQuC7p9reiqpI4L2ystbC
xjVwYc0BBAFaaywcFBfhtmyvxRZRlJvY/R/KKnav8B3nJaFgrm7SFCk5qK+qwkyJxNh96lep71lt9koK
/ZczlhXt/3en98YqLkoXPH7EHC2SxJvWlTS1degS6ZKDcIWiPRtKMKvbk1Q6fPf2/+nVu4NKNUquLbr0
ozC/o+S3V0mV5ZGqFrm2BE/3ofG3pwAHZqCV49dZ5V7TyE/IvmKhdYNLwIvMiB3+tm8Pz7z7bV8GfVyQ
hlh41fRA54qEBhfT6pTVm+vWvHHw4HVCgDRlaQi8vIcefxRWiZ3G1sxvdkadmNc0iAIfci8+QQcZvqM1
IGKnIGWr0GxNjyjnow77RlAGUlCjWtHxOfFzpE2fzr8qygJ0PkYjMGOV6OXmXeemPucS/8aJrF7OwpM4
gKPozLqWuGkK7z3bQx5sWOjXQYoWy2W73ZBc5fOxlG02cNVGAHBJVbsipLBobE49rh8KpXHeygq86Ru3
uuKSylTz1lo3DhcNnqGMDBs9O2cdZCxOAKAgwztE6iMDcHnZq+bsi6JRqfZFo6tkIMMKKUOSxxU4E7fZ
gCxQfgXFyRCNIE3bDoSYYUiQZg5E9iBkOyLc7OWJ4l9e0LH51ChfmiRuBR6LeK6IDTjYI8d1lPvcWMiQ
hfTaAbk1ZU8C2/QCxZAGSrttlb69NJoGGmkwBFo/5dBLNw4aHO7oOKz/xcJuOxuVzy8vzz1WPmuwXpOV
i16sU/vz9Lzr0tSj6wcqgrA46nXQmPN/570vkkGjcAzXnVXXQecZ3H1DtvJJl0F+hmAEryqfn7N8xpJz
kLPK/jPxX+LtmzGsrdPnBB5iCs3oJDzAL352zmf/Ur+KFHM38IW+0AyWXawHo2g++0KzBSxh5o9/C2iP
kX4zW/Q/GZrppsPQ/zsAAP//6HM6CPALAAA=
`,
	},

	"/topo-sort": {
		name:  "topo-sort",
		local: `topo-sort`,
		isDir: true,
	},

	"/topo-sort/.git": {
		name:  ".git",
		local: `topo-sort/.git`,
		isDir: true,
	},

	"/topo-sort/.git/hooks": {
		name:  "hooks",
		local: `topo-sort/.git/hooks`,
		isDir: true,
	},

	"/topo-sort/.git/info": {
		name:  "info",
		local: `topo-sort/.git/info`,
		isDir: true,
	},

	"/topo-sort/.git/logs": {
		name:  "logs",
		local: `topo-sort/.git/logs`,
		isDir: true,
	},

	"/topo-sort/.git/logs/refs": {
		name:  "refs",
		local: `topo-sort/.git/logs/refs`,
		isDir: true,
	},

	"/topo-sort/.git/logs/refs/heads": {
		name:  "heads",
		local: `topo-sort/.git/logs/refs/heads`,
		isDir: true,
	},

	"/topo-sort/.git/logs/refs/remotes": {
		name:  "remotes",
		local: `topo-sort/.git/logs/refs/remotes`,
		isDir: true,
	},

	"/topo-sort/.git/logs/refs/remotes/origin": {
		name:  "origin",
		local: `topo-sort/.git/logs/refs/remotes/origin`,
		isDir: true,
	},

	"/topo-sort/.git/objects": {
		name:  "objects",
		local: `topo-sort/.git/objects`,
		isDir: true,
	},

	"/topo-sort/.git/objects/4f": {
		name:  "4f",
		local: `topo-sort/.git/objects/4f`,
		isDir: true,
	},

	"/topo-sort/.git/objects/7f": {
		name:  "7f",
		local: `topo-sort/.git/objects/7f`,
		isDir: true,
	},

	"/topo-sort/.git/objects/f2": {
		name:  "f2",
		local: `topo-sort/.git/objects/f2`,
		isDir: true,
	},

	"/topo-sort/.git/objects/info": {
		name:  "info",
		local: `topo-sort/.git/objects/info`,
		isDir: true,
	},

	"/topo-sort/.git/objects/pack": {
		name:  "pack",
		local: `topo-sort/.git/objects/pack`,
		isDir: true,
	},

	"/topo-sort/.git/refs": {
		name:  "refs",
		local: `topo-sort/.git/refs`,
		isDir: true,
	},

	"/topo-sort/.git/refs/heads": {
		name:  "heads",
		local: `topo-sort/.git/refs/heads`,
		isDir: true,
	},

	"/topo-sort/.git/refs/remotes": {
		name:  "remotes",
		local: `topo-sort/.git/refs/remotes`,
		isDir: true,
	},

	"/topo-sort/.git/refs/remotes/origin": {
		name:  "origin",
		local: `topo-sort/.git/refs/remotes/origin`,
		isDir: true,
	},

	"/topo-sort/.git/refs/tags": {
		name:  "tags",
		local: `topo-sort/.git/refs/tags`,
		isDir: true,
	},
}

var _escDirs = map[string][]os.FileInfo{

	"topo-sort": {
		_escData["/topo-sort/.git"],
		_escData["/topo-sort/.gitignore"],
		_escData["/topo-sort/LICENSE"],
		_escData["/topo-sort/README.md"],
		_escData["/topo-sort/package.json"],
		_escData["/topo-sort/randomfile.txt"],
		_escData["/topo-sort/tsort.js"],
	},

	"topo-sort/.git": {
		_escData["/topo-sort/.git/COMMIT_EDITMSG"],
		_escData["/topo-sort/.git/FETCH_HEAD"],
		_escData["/topo-sort/.git/HEAD"],
		_escData["/topo-sort/.git/config"],
		_escData["/topo-sort/.git/description"],
		_escData["/topo-sort/.git/hooks"],
		_escData["/topo-sort/.git/index"],
		_escData["/topo-sort/.git/info"],
		_escData["/topo-sort/.git/logs"],
		_escData["/topo-sort/.git/objects"],
		_escData["/topo-sort/.git/packed-refs"],
		_escData["/topo-sort/.git/refs"],
	},

	"topo-sort/.git/hooks": {
		_escData["/topo-sort/.git/hooks/applypatch-msg.sample"],
		_escData["/topo-sort/.git/hooks/commit-msg.sample"],
		_escData["/topo-sort/.git/hooks/fsmonitor-watchman.sample"],
		_escData["/topo-sort/.git/hooks/post-update.sample"],
		_escData["/topo-sort/.git/hooks/pre-applypatch.sample"],
		_escData["/topo-sort/.git/hooks/pre-commit.sample"],
		_escData["/topo-sort/.git/hooks/pre-merge-commit.sample"],
		_escData["/topo-sort/.git/hooks/pre-push.sample"],
		_escData["/topo-sort/.git/hooks/pre-rebase.sample"],
		_escData["/topo-sort/.git/hooks/pre-receive.sample"],
		_escData["/topo-sort/.git/hooks/prepare-commit-msg.sample"],
		_escData["/topo-sort/.git/hooks/push-to-checkout.sample"],
		_escData["/topo-sort/.git/hooks/update.sample"],
	},

	"topo-sort/.git/info": {
		_escData["/topo-sort/.git/info/exclude"],
	},

	"topo-sort/.git/logs": {
		_escData["/topo-sort/.git/logs/HEAD"],
		_escData["/topo-sort/.git/logs/refs"],
	},

	"topo-sort/.git/logs/refs": {
		_escData["/topo-sort/.git/logs/refs/heads"],
		_escData["/topo-sort/.git/logs/refs/remotes"],
	},

	"topo-sort/.git/logs/refs/heads": {
		_escData["/topo-sort/.git/logs/refs/heads/dev"],
		_escData["/topo-sort/.git/logs/refs/heads/master"],
	},

	"topo-sort/.git/logs/refs/remotes": {
		_escData["/topo-sort/.git/logs/refs/remotes/origin"],
	},

	"topo-sort/.git/logs/refs/remotes/origin": {
		_escData["/topo-sort/.git/logs/refs/remotes/origin/HEAD"],
		_escData["/topo-sort/.git/logs/refs/remotes/origin/dev"],
	},

	"topo-sort/.git/objects": {
		_escData["/topo-sort/.git/objects/4f"],
		_escData["/topo-sort/.git/objects/7f"],
		_escData["/topo-sort/.git/objects/f2"],
		_escData["/topo-sort/.git/objects/info"],
		_escData["/topo-sort/.git/objects/pack"],
	},

	"topo-sort/.git/objects/4f": {
		_escData["/topo-sort/.git/objects/4f/c2ceaef805dfa5bbccc08feef279a5e4309dd7"],
	},

	"topo-sort/.git/objects/7f": {
		_escData["/topo-sort/.git/objects/7f/0ee74d75d062d8f2918ee576e087ea3dd7f6c9"],
	},

	"topo-sort/.git/objects/f2": {
		_escData["/topo-sort/.git/objects/f2/010ee942a47bec0ca7e8f04240968ea5200735"],
	},

	"topo-sort/.git/objects/info": {},

	"topo-sort/.git/objects/pack": {
		_escData["/topo-sort/.git/objects/pack/pack-6179faab20f2d649a12fd52aab3c8d6e32b27dcd.idx"],
		_escData["/topo-sort/.git/objects/pack/pack-6179faab20f2d649a12fd52aab3c8d6e32b27dcd.pack"],
	},

	"topo-sort/.git/refs": {
		_escData["/topo-sort/.git/refs/heads"],
		_escData["/topo-sort/.git/refs/remotes"],
		_escData["/topo-sort/.git/refs/tags"],
	},

	"topo-sort/.git/refs/heads": {
		_escData["/topo-sort/.git/refs/heads/dev"],
		_escData["/topo-sort/.git/refs/heads/master"],
	},

	"topo-sort/.git/refs/remotes": {
		_escData["/topo-sort/.git/refs/remotes/origin"],
	},

	"topo-sort/.git/refs/remotes/origin": {
		_escData["/topo-sort/.git/refs/remotes/origin/HEAD"],
		_escData["/topo-sort/.git/refs/remotes/origin/dev"],
	},

	"topo-sort/.git/refs/tags": {},
}
